apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-dep20
  labels:
    k8s-app: gpu-dep20

spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: gpu-dep20
  template:
    metadata:
      labels:
        k8s-app: gpu-dep20
    spec:
      containers:
      - name: gpu-container
        image: ruchirgarg05/bert_lrl
        command: ["sleep", "infinity"]
        resources:
          limits:
            memory: 20Gi
            cpu: 2 
            nvidia.com/gpu: 1
          requests:
            memory: 20Gi
            cpu: 2
            nvidia.com/gpu: 1
        volumeMounts:
          - mountPath: /base_vol_central
            name: base-vol-central
 
      volumes:
      - name: base-vol-central
        persistentVolumeClaim:
          claimName: base-vol-central
        
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                - us-central
