apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-dep
  labels:
    k8s-app: gpu-dep

spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: gpu-dep
  template:
    metadata:
      labels:
        k8s-app: gpu-dep
    spec:
      containers:
      - name: gpu-container
        image: gitlab-registry.nrp-nautilus.io/ruchirgarg005/regitry:latest 
        command: ["sleep", "infinity"]
        resources:
          limits:
            memory: 36Gi
            cpu: 4
            nvidia.com/gpu: 1
          requests:
            memory: 36Gi
            cpu: 4
            nvidia.com/gpu: 1
        volumeMounts:
          - mountPath: /base_vol
            name: base-vol
          - mountPath: /local
            name: local-vol
 
      volumes:
      - name: base-vol
        persistentVolumeClaim:
          claimName: base-vol
      - name: local-vol
        hostPath:
          path: /c/Users/ruchi/Documents/GitHub
          type: Directory
        
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                - us-west
