apiVersion: v1
kind: Pod
metadata:
  name: gpu-base
spec:
  containers:
  - name: gpu-container
    image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp:latest
    command: ["sleep", "infinity"]
    resources:
      limits:
        nvidia.com/gpu: 1
    volumeMounts:
      - mountPath: /base_vol
        name: base-vol
    env:
      - name: GIT_USERNAME
        valueFrom: 
          secretKeyRef:
            name: harshv834-github
            key: user
      - name: GIT_PASSWORD
        valueFrom: 
          secretKeyRef:
            name: harshv834-github
            key: password
 
  restartPolicy: Never
  volumes:
    - name: base-vol
      persistentVolumeClaim:
        claimName: base-vol
        
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/region
            operator: In
            values:
            - us-west
