apiVersion: v1
kind: Pod
metadata:
  name: gpu-base
spec:
  containers:
  - name: gpu-container
    image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp:latest
    command: ["sleep", "infinity"]
    resources:
      limits:
        cpu : 8
        memory : 32Gi
        nvidia.com/gpu: 1
      requests:
        cpu : 8
        memory : 32Gi
        nvidia.com/gpu: 1
    volumeMounts:
      - mountPath: /base_vol
        name: base-vol
      - name: ssh-key-volume
        mountPath: "/etc/ssh-key"
        readOnly: true
 
  restartPolicy: Never
  volumes:
    - name: base-vol
      persistentVolumeClaim:
        claimName: base-vol
    - name: ssh-key-volume
      secret: 
        secretName: harshv834-github-key
        
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/region
            operator: In
            values:
            - us-west
